### ISSUE TITLE
Character metadata should be optional

### ISSUE THREAD

**Issue by Evil-Crab** [MediaBrowser/Emby.Plugins.AniList#3]
Currently, this plugin returns both VA and Characters as a series cast. IMHO this should be configurable.

https://github.com/MediaBrowser/Emby.Plugins.AniList/blob/4256478d2e42ba09c776d5d68482a3064dcee7f7/Emby.Plugins.AniList/api.cs#L235

**Comment by LukePulverenti** [comment]
Hi, this is what I merged in from you, right?

**Comment by Evil-Crab** [comment]
yeah
